import { createClient, SanityClient } from '@sanity/client';

/*===============================================
|=                SanityService                 =
===============================================*/

/**
 * SANITY CMS SERVICE
 *
 * Manages document creation and management in Sanity CMS.
 * Handles draft creation, approval workflow, and document queries.
 *
 * Key Features:
 * - Draft Management: Creates draft documents for review workflow
 * - Approval System: Approve/reject drafts with metadata tracking
 * - Document Queries: Fetch drafts and published content
 * - Multi-tenant: Works with any Sanity project via credentials
 *
 * Workflow:
 * 1. Create Draft: LLM-generated content saved as draft
 * 2. Review: Editors review drafts in Sanity Studio
 * 3. Approve/Reject: Mark drafts as approved or rejected
 * 4. Publish: Approved drafts can be published (future feature)
 *
 * Document Structure:
 * - Standard Sanity fields (_type, _id, etc.)
 * - Custom metadata: _approved, _rejected flags
 * - Content fields: Generated by LLM based on schema
 *
 * Security:
 * - Uses encrypted Sanity tokens from configuration
 * - Validates all inputs before document creation
 * - No direct client access - all operations server-side
 */

export class SanityService {
  private client: SanityClient;

  constructor(
    projectId: string,
    token: string,
    dataset: string = 'production'
  ) {
    this.client = createClient({
      projectId,
      token,
      dataset,
      useCdn: false,
      apiVersion: '2023-03-01',
    });
  }

  // Create a draft document
  async createDraft(schemaType: string, document: Record<string, any>) {
    const docWithMeta = {
      ...document,
      _type: schemaType,
      _approved: false,
      _rejected: false,
    };
    return this.client.create(docWithMeta);
  }

  // Query draft documents
  async queryDrafts(options: { type?: string }) {
    const { type } = options;
    const query = `*[_type == "${type || 'article'}" && _approved == false && _rejected == false]`;
    return this.client.fetch(query);
  }

  // Approve a draft (marks as approved, doesn't publish yet)
  async approveDocument(documentId: string) {
    return this.client
      .patch(documentId)
      .set({ _approved: true, _rejected: false })
      .commit();
  }

  // Reject a draft
  async rejectDocument(documentId: string) {
    return this.client
      .patch(documentId)
      .set({ _approved: false, _rejected: true })
      .commit();
  }
}

export function createSanityService(
  projectId: string,
  token: string,
  dataset?: string
): SanityService {
  return new SanityService(projectId, token, dataset);
}
